name: Node.js CI - Testing Flow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testing-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install and Build
        run: npm install && npm ci && npm run build --if-present
      - name: Testing functions and modules
        run: npm test
